### PR TITLE
Logging mha2nnunet

### PR DESCRIPTION
**Pull request by joeranbosma**
Write the traceback to the log when an error occurs, instead of silently continuing.

### CODE REVIEW

**Comment by joeranbosma** [comment]
The tests for Windows fail for some reason...

**Comment by joeranbosma** [comment]
@snorthman I've updated the Python versions to test, and the tests are now running successfully. However, the test to verify preprocessing runs as expected through the command line interface fails on Windows. Would this be something you could debug? I don't have access to Windows... Otherwise, shall we deprecate support for Windows?

**Comment by snorthman** [comment]
I will try to fix it first. What is the urgency on this?

**Comment by joeranbosma** [comment]
The urgency is low, but it would be good to resolve the issue at some point.

**Review by snorthman — APPROVED** [review]

**Pull request merged**
